;; ---------------------------------------------------------
;; App info file handling
;;
;; Functions to generate, write, and read the app.edn file
;; which contains a map of application information such as
;; name and version.
;;
;; ---------------------------------------------------------

(ns app
  "Functions to generate, write, and read the `app.edn` file.
  This file serve the same purpose as the `version.edn` file found in other
  projects: it contains current version information as well as some
  additional info such as the application name.
  Unlike `version.edn`, `app.edn`:
  - is generated by `build.clj` which centralize all project information and uses
    `write-app-info` defined in this namespace
  - contains the app and cli name along the version numbers
  "
  (:require [clojure.edn :as edn]
            [clojure.java.io :as io]))

(def app-filename "app.edn")
(def app-file (io/file "resources" app-filename))
(when-not (or (-> app-file .exists) (io/resource app-filename))
  (println (str "WARNING: " app-filename " not found")))

(defn write-app-info
  "Write content to the app file."
  [content]
  (io/make-parents app-file)
  (spit app-file (pr-str content)))

(defn gen-app-info-with [s]
  {:app-name s
   :app-home s
   :app-cli s
   :major-version s
   :minor-version s
   :version-string s})

(def app-info
  (try
    (-> (io/resource app-filename) slurp edn/read-string)
    (catch Throwable _
      (gen-app-info-with (str "Failed to read " app-filename)))))
(def app-name (:app-name app-info))
(def app-home (:app-home app-info))
(def app-cli (:app-cli app-info))
(def major-version (:major-version app-info))
(def minor-version (:minor-version app-info))
(def version-string (:version-string app-info))
